name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Lint
        run: ./gradlew spotlessCheck

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: ["17", "21"]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Start containers
        run: docker compose up -d minio redis

      - name: Run the tests
        run: ./gradlew test --info

      - name: Shutdown containers
        if: always()
        run: docker compose down --remove-orphans -v --timeout 3 || true
