name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Lint
        run: ./gradlew spotlessCheck

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Start containers
        run: |
          docker compose up -d \
            mariadb \
            mysql \
            postgres \
            minio \
            redis

      - name: Provision databases
        run: |
          docker compose up --exit-code-from mariadb-init mariadb-init
          docker compose up --exit-code-from mysql-init mysql-init
          docker compose up --exit-code-from postgres-init postgres-init

      - name: Run the tests
        run: ./gradlew test

      - name: Shutdown containers
        if: always()
        run: docker compose down --remove-orphans -v --timeout 3 || true
